import { useState, useEffect } from 'react';

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const defaultEndpoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint
  });
  const {current} = page;

  return (
    <div className="flex flex-col items-center justify-center w-screen min-h-screen py-2 ">
      <Head>
        <title>Wubba Lubba Dub Dub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center text-center ">
        <h1 className="font-bold text-6xl p-5">Wubba Lubba Dub Dub</h1>

        <p className="mb-10 text-xl">Rick and Morty Wiki</p>

        <ul className={styles.grid}>
          {results.map((result) => {
            const { id, name, image } = result;

            return (
              <li key={id} className={styles.card}>
                <a href="https://nextjs.org/docs" className="">
                  <img src={ image } alt={ name } />
                  <h3 className="font-bold text-2xl">{ name }</h3>
                </a>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
